//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyAgencyWebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentDemand
    {
        public int Id { get; set; }
        public Nullable<byte> MinFloor { get; set; }
        public Nullable<byte> MaxFloor { get; set; }
    
        public virtual BuildingDemand BuildingDemand { get; set; }
    }
}
