//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyAgencyWebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demand()
        {
            this.Deal = new HashSet<Deal>();
        }
    
        public int DemandId { get; set; }
        public int ClientId { get; set; }
        public int AgentId { get; set; }
        public Nullable<int> RealEstateTypeId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> MinPrice { get; set; }
        public Nullable<int> MaxPrice { get; set; }
        public Nullable<decimal> MinArea { get; set; }
        public Nullable<decimal> MaxArea { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual BuildingDemand BuildingDemand { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deal { get; set; }
        public virtual PropertyAddress PropertyAddress { get; set; }
        public virtual RealEstateType RealEstateType { get; set; }
        public virtual LandDemand LandDemand { get; set; }
    }
}
