//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyAgencyWebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventTypeId { get; set; }
        public string Comment { get; set; }
        public int AgentId { get; set; }
        public string UUID { get; set; }
        public long DateTime { get; set; }
        public Nullable<int> DurationInSeconds { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual EventType EventType { get; set; }
    }
}
